### ISSUE TITLE
Unable to run Custom Trained Model on Demo Prediction Code

### ISSUE THREAD

**Issue by NaeemKhanNiazi** [uzairmughal20/Floor-Segmentation#1]
Hi @uzairmughal20 

Thank you very much for such a amazing work . I trained the model with the given code in the repository. After completing the training, I get a weight file but When I try to run the code with weight file.I am facing error ,

```
ValueError: Layer count mismatch when loading weights from file. Model expected 229 layers, found 277 saved layers.

```

Can you give steps for converting the model to support the prediction code. Thanks

**Comment by uzair-mughal** [comment]
Hey, thanks for giving my code a try!
Can you please mention where exactly you get this error and if you have changed anything in any of those files so I can trace the problem further?
Regards.

**Comment by NaeemKhanNiazi** [comment]
@uzairmughal20 Thank you for response , I have not changed anything in the code . I used the 
- Training note for training (given by you).
- After training , I get a .h5 weight(which is around 300 mbs (in your case it 70 mb with json file)) file which  I replace with the weight file(given by you).

```
Traceback (most recent call last):
  File "/home/pc/Downloads/Compressed/Floor-Segmentation-master/prediction.py", line 91, in <module>
    main()
  File "/home/pc/Downloads/Compressed/Floor-Segmentation-master/prediction.py", line 86, in main
    model = get_model()
  File "/home/pc/Downloads/Compressed/Floor-Segmentation-master/prediction.py", line 28, in get_model
    loaded_model.load_weights("./model_files/model.h5")
  File "/home/pc/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/pc/.local/lib/python3.10/site-packages/keras/saving/hdf5_format.py", line 817, in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 229 layers, found 277 saved layers.

```

How actually you generated .h5 weight file with .json file. Have you used any post conversion?

**Comment by NaeemKhanNiazi** [comment]
Hi @uzairmughal20 

I resolve the issue. Actually problem was

Your current training code
- Save the weight File
- It does not save the architecture of the model.
- Eventually prediction code throw error on custom trained model.

 Please add the following code in the end of the notebook

[Training-Notebook](https://github.com/uzairmughal20/Floor-Segmentation/blob/master/train/train.ipynb)

```
from keras.models import model_from_json
# serialize model to json
json_model = model.to_json()
#save the model architecture to JSON file
with open('model.json', 'w') as json_file:
    json_file.write(json_model)
```

Above code snippet will save a json file which have architecture of the model.

**Comment by uzair-mughal** [comment]
Thanks @NaeemKhanNiazi, will add it for sure.
